const crypto=require("crypto"); const database=require("../../database/database"); const repository=require("./repository"); const validator=require("./validator"); const sourceMetadata=require("./sourceMetadata");
function detectPlatform(sourceUrl){if(!sourceUrl)return null;try{const host=new URL(sourceUrl).hostname.toLowerCase().replace(/^www\./,"");if(host.endsWith("instagram.com"))return"instagram";if(host.endsWith("tiktok.com"))return"tiktok";if(host.endsWith("youtube.com")||host==="youtu.be")return"youtube";if(host.endsWith("pinterest.com")||host.endsWith("pin.it"))return"pinterest";return host;}catch(_){return null;}}
function mapItem(row,userId){if(!row)return null;return{public_id:row.public_id,source_type:row.source_type,source_url:row.source_url,source_platform:row.source_platform,source_image_url:row.source_image_url||null,source_page_title:row.source_page_title||null,title:row.title,note:row.note,status:row.status,saved_at:row.saved_at,created_at:row.created_at,updated_at:row.updated_at,created_by_name:row.created_by_name||null,workspace_assignment_count:Number(row.workspace_assignment_count)||1,can_manage:Number(row.created_by_user_id)===Number(userId)};}
async function listItems(workspaceId,status,userId){return (await repository.listItems(workspaceId,status)).map(row=>mapItem(row,userId));}
async function previewSource(payload){const validation=validator.validatePreview(payload);if(validation.error)return validation;return {value:await sourceMetadata.preview(validation.value.source_url)};}
async function createItem({workspaceId,userId,payload}){const validation=validator.validateCreate(payload);if(validation.error)return validation;const value=validation.value;let meta={title:value.source_page_title,image_url:value.source_image_url,final_url:value.source_url};if(value.source_url&&(!meta.title||!meta.image_url))meta=await sourceMetadata.preview(value.source_url);const publicId=crypto.randomUUID();await database.run("BEGIN");try{const walletItemId=await repository.insertItem({public_id:publicId,workspace_id:workspaceId,created_by_user_id:userId,source_type:value.source_type,source_url:meta.final_url||value.source_url,source_platform:detectPlatform(meta.final_url||value.source_url),source_external_id:null,source_image_url:value.source_image_url||meta.image_url||null,source_page_title:value.source_page_title||meta.title||null,title:value.title||meta.title||null,note:value.note});await repository.addWorkspaceAssignment({walletItemId,workspaceId,assignedByUserId:userId});await database.run("COMMIT");return {value:mapItem(await repository.findByPublicId(workspaceId,publicId),userId)};}catch(error){await database.run("ROLLBACK").catch(()=>{});throw error;}}
async function updateItem({workspaceId,userId,publicId,payload}){const validation=validator.validateUpdate(payload);if(validation.error)return validation;const visible=await repository.findByPublicId(workspaceId,publicId);if(!visible)return{notFound:true};if(Number(visible.created_by_user_id)!==Number(userId))return{forbidden:true,error:"Nur der Ersteller kann diese Inspiration bearbeiten."};const fields={...validation.value};if(Object.prototype.hasOwnProperty.call(fields,'source_url'))fields.source_platform=detectPlatform(fields.source_url);const changed=await repository.updateItemByOwner(publicId,userId,fields);if(!changed)return{notFound:true};return{value:mapItem(await repository.findByPublicId(workspaceId,publicId),userId)};}
async function deleteItem(workspaceId,userId,publicId){const visible=await repository.findByPublicId(workspaceId,publicId);if(!visible)return{notFound:true};if(Number(visible.created_by_user_id)!==Number(userId))return{forbidden:true,error:"Nur der Ersteller kann diese Inspiration löschen."};return{deleted:(await repository.deleteItemByOwner(publicId,userId))>0};}
module.exports={listItems,createItem,updateItem,deleteItem,detectPlatform,previewSource};
