const { run, all, get } = require('../../database/database');
function clean(v,max=255){return String(v??'').trim().slice(0,max)}
function json(v){try{return JSON.stringify(v&&typeof v==='object'?v:{})}catch{return '{}'}}
function parseJson(v){try{return JSON.parse(v||'{}')||{}}catch{return {}}}
function safeDays(v){return Math.min(365,Math.max(1,Number(v)||28))}
function deviceFromUa(ua=''){const s=String(ua||'');return{device:/iPad|Tablet|Android(?!.*Mobile)/i.test(s)?'Tablet':/Mobi|Android|iPhone|iPod/i.test(s)?'Mobile':'Desktop',browser:/Edg\//.test(s)?'Edge':/Firefox\//.test(s)?'Firefox':/Chrome\//.test(s)?'Chrome':/Safari\//.test(s)&&!/Chrome\//.test(s)?'Safari':'Andere',os:/Windows/i.test(s)?'Windows':/Android/i.test(s)?'Android':/iPhone|iPad|iPod/i.test(s)?'iOS/iPadOS':/Mac OS X|Macintosh/i.test(s)?'macOS':/Linux/i.test(s)?'Linux':'Andere'}}
function period(opts={}){const from=/^\d{4}-\d{2}-\d{2}$/.test(String(opts.from||''))?String(opts.from):null,to=/^\d{4}-\d{2}-\d{2}$/.test(String(opts.to||''))?String(opts.to):null;if(from&&to)return{sql:`created_at>=datetime(?) AND created_at<datetime(?, '+1 day')`,params:[from,to],label:{from,to}};const d=safeDays(opts.days);return{sql:`created_at>=datetime('now',?)`,params:[`-${d} days`],label:{days:d}}}
function peScope(workspaceId,opts={},alias='pe'){const p=period(opts),w=workspaceId?`${alias}.workspace_id=? AND `:'';return{sql:w+p.sql.replaceAll('created_at',`${alias}.created_at`),params:[...(workspaceId?[workspaceId]:[]),...p.params],label:p.label}}
async function recordEvent({eventName,eventCategory='module',userId=null,workspaceId=null,sessionId='',path='',method='',entityType='',entityReference='',properties={}}){const name=clean(eventName,80);if(!name)return;await run(`INSERT INTO product_events(event_name,event_category,user_id,workspace_id,session_id,path,method,entity_type,entity_reference,properties_json) VALUES(?,?,?,?,?,?,?,?,?,?)`,[name,clean(eventCategory,40)||'module',userId||null,workspaceId||null,clean(sessionId,120)||null,clean(path,300)||null,clean(method,12)||null,clean(entityType,50)||null,clean(entityReference,160)||null,json(properties)])}
function classifyRequest(method,path){const p=String(path||'').split('?')[0];if(method==='POST'&&p==='/recipes')return['recipe_created','module','recipe'];if(method==='PUT'&&/^\/recipes\/\d+$/.test(p))return['recipe_updated','module','recipe'];if(method==='POST'&&p==='/wallet')return['wallet_saved','module','wallet'];if((method==='PUT'||method==='POST')&&/\/wallet\/[^/]+\/recipe-links$/.test(p))return['wallet_recipe_connected','connection','wallet_recipe'];if(method==='PUT'&&/\/wallet\/[^/]+\/food-moment-links$/.test(p))return['wallet_food_moment_connected','connection','wallet_food_moment'];if(method==='POST'&&p==='/food-moments')return['food_moment_created','module','food_moment'];if(method==='PATCH'&&/^\/food-moments\/[^/]+$/.test(p))return['food_moment_updated','module','food_moment'];if(method==='POST'&&/\/food-moments\/[^/]+\/repeat$/.test(p))return['food_moment_repeated','connection','food_moment'];if(method==='PUT'&&p==='/planning/slot')return['planning_slot_saved','connection','planning'];if(method==='DELETE'&&p==='/planning/slot')return['planning_slot_removed','connection','planning'];if(method==='POST'&&/\/meal_plans\/\d+\/apply$/.test(p))return['week_template_applied','connection','planning'];if(method==='POST'&&p==='/meal_plans')return['week_template_created','module','planning_template'];if(method==='POST'&&/\/shopping-list\/import\/recipe\/\d+$/.test(p))return['recipe_to_shopping','connection','shopping'];if(method==='POST'&&/\/shopping-list\/import\/food-moment\/[^/]+$/.test(p))return['food_moment_to_shopping','connection','shopping'];if(method==='POST'&&p==='/shopping-list/manual')return['shopping_manual_added','module','shopping'];if(method==='PATCH'&&p==='/shopping-list/group')return['shopping_item_toggled','module','shopping'];if(method==='DELETE'&&p==='/shopping-list/completed')return['shopping_completed_cleared','module','shopping'];return null}
function trackingMiddleware(req,res,next){const started=Date.now();res.on('finish',()=>{if(res.statusCode>=400||req.path.startsWith('/analytics'))return;const match=classifyRequest(req.method,req.path);if(!match)return;(async()=>{const[eventName,eventCategory,entityType]=match;const ref=req.params?.publicId||req.params?.id||req.body?.public_id||req.body?.recipe_id||'';let userId=req.auth?.user?.id||null,workspaceId=req.workspaceId||null;if(!userId){const token=(String(req.headers.authorization||'').match(/^Bearer\s+(.+)$/i)||[])[1];if(token){const auth=await require('../../core/identity/service').authenticateToken(token.trim());userId=auth?.user?.id||null}}if(userId&&!workspaceId){const ctx=await require('../../core/workspaces/service').resolveWorkspaceContextForUser(userId,String(req.headers['x-workspace-id']||'').trim());workspaceId=ctx?.workspaceId||null}if(!userId||!workspaceId)return;await recordEvent({eventName,eventCategory,entityType,entityReference:ref,userId,workspaceId,sessionId:req.headers['x-product-session-id']||'',path:req.path,method:req.method,properties:{duration_ms:Date.now()-started,source:req.body?.source_code||null}})})().catch(e=>console.warn('Analytics event konnte nicht gespeichert werden:',e.message))});next()}
async function getSummary(workspaceId,opts={}){const s=peScope(workspaceId,opts);const P=s.params;const [totals,events,daily,users,moduleRows,dwellRows,friction,userSignals]=await Promise.all([
get(`SELECT COUNT(*) total_events,COUNT(DISTINCT user_id) active_users,COUNT(DISTINCT session_id) sessions,SUM(CASE WHEN event_category='connection' THEN 1 ELSE 0 END) connection_events FROM product_events pe WHERE ${s.sql}`,P),
all(`SELECT event_name,event_category,COUNT(*) count,COUNT(DISTINCT user_id) users FROM product_events pe WHERE ${s.sql} GROUP BY event_name,event_category ORDER BY count DESC,event_name`,P),
all(`SELECT date(pe.created_at) day,COUNT(*) events,COUNT(DISTINCT user_id) users,SUM(CASE WHEN event_category='connection' THEN 1 ELSE 0 END) connections FROM product_events pe WHERE ${s.sql} GROUP BY date(pe.created_at) ORDER BY day`,P),
all(`SELECT pe.user_id,u.display_name,u.email,COUNT(*) events,COUNT(DISTINCT pe.session_id) sessions,SUM(CASE WHEN pe.event_category='connection' THEN 1 ELSE 0 END) connections,MIN(pe.created_at) first_seen,MAX(pe.created_at) last_seen FROM product_events pe LEFT JOIN users u ON u.id=pe.user_id WHERE ${s.sql} AND pe.user_id IS NOT NULL GROUP BY pe.user_id,u.display_name,u.email ORDER BY events DESC,last_seen DESC`,P),
all(`SELECT pe.path,COUNT(*) views,COUNT(DISTINCT pe.user_id) users FROM product_events pe WHERE ${s.sql} AND pe.event_name='page_view' GROUP BY pe.path ORDER BY views DESC`,P),
all(`SELECT pe.path,pe.properties_json FROM product_events pe WHERE ${s.sql} AND pe.event_name='dwell_time'`,P),
all(`SELECT event_name,COUNT(*) count,COUNT(DISTINCT user_id) users FROM product_events pe WHERE ${s.sql} AND event_category='friction' GROUP BY event_name ORDER BY count DESC`,P),
all(`SELECT user_id,event_name,event_category FROM product_events pe WHERE ${s.sql} AND user_id IS NOT NULL`,P)]);
const eventMap=Object.fromEntries(events.map(e=>[e.event_name,Number(e.count)])),dwell={};for(const r of dwellRows){const ms=Number(parseJson(r.properties_json).duration_ms||0);if(ms>0&&ms<3600000)(dwell[r.path||'(unbekannt)']??=[]).push(ms)}const modules=moduleRows.map(r=>{const v=dwell[r.path]||[];return{...r,views:+r.views,users:+r.users,avg_dwell_ms:v.length?Math.round(v.reduce((a,b)=>a+b,0)/v.length):0}});const per=new Map();for(const e of userSignals){if(!per.has(e.user_id))per.set(e.user_id,{events:new Set(),categories:new Set()});per.get(e.user_id).events.add(e.event_name);per.get(e.user_id).categories.add(e.event_category)}const ac=per.size||0,mc=fn=>[...per.values()].filter(fn).length;const concept={food_moment_users:mc(x=>x.events.has('food_moment_created')),connection_users:mc(x=>x.categories.has('connection')),planning_users:mc(x=>x.events.has('planning_slot_saved')||x.events.has('week_template_applied')),cross_module_users:mc(x=>x.events.size>=4)};concept.food_moment_rate=ac?Math.round(concept.food_moment_users/ac*100):0;concept.connection_rate=ac?Math.round(concept.connection_users/ac*100):0;
return{range:s.label,totals:{...totals,total_events:+(totals?.total_events||0),active_users:+(totals?.active_users||0),sessions:+(totals?.sessions||0),connection_events:+(totals?.connection_events||0)},events:events.map(e=>({...e,count:+e.count,users:+e.users})),daily:daily.map(x=>({...x,events:+x.events,users:+x.users,connections:+(x.connections||0)})),users:users.map(u=>({...u,events:+u.events,sessions:+u.sessions,connections:+(u.connections||0)})),modules,friction:friction.map(x=>({...x,count:+x.count,users:+x.users})),concept_metrics:concept,retention:{},journey_signals:{inspiration:(eventMap.wallet_saved||0)+(eventMap.wallet_recipe_connected||0)+(eventMap.wallet_food_moment_connected||0),recipe_planning:(eventMap.planning_slot_saved||0)+(eventMap.food_moment_created||0),occasion:(eventMap.food_moment_created||0)+(eventMap.food_moment_updated||0),weekly_planning:(eventMap.planning_slot_saved||0)+(eventMap.week_template_applied||0),shopping:(eventMap.recipe_to_shopping||0)+(eventMap.food_moment_to_shopping||0)+(eventMap.shopping_item_toggled||0)}}}
async function getLogins(workspaceId,opts={}){const p=period(opts);let where=p.sql.replaceAll('created_at','s.created_at'),params=[...p.params];let join='';if(workspaceId){join='JOIN workspace_memberships wm ON wm.user_id=u.id AND wm.workspace_id=?';params=[workspaceId,...params]}const rows=await all(`SELECT s.id,s.user_id,u.display_name,u.email,s.created_at login_at,s.last_seen_at,s.expires_at,s.revoked_at,s.user_agent FROM user_sessions s JOIN users u ON u.id=s.user_id ${join} WHERE ${where} GROUP BY s.id ORDER BY s.created_at DESC LIMIT 5000`,params);return rows.map(r=>({...r,...deviceFromUa(r.user_agent)}))}
async function getJourneys(workspaceId,opts={}){const s=peScope(workspaceId,opts),lim=Math.min(5000,Math.max(10,Number(opts.limit)||500));const rows=await all(`SELECT pe.id,pe.user_id,u.display_name,u.email,w.public_id workspace_public_id,w.name workspace_name,pe.session_id,pe.event_name,pe.event_category,pe.path,pe.entity_type,pe.entity_reference,pe.properties_json,pe.created_at FROM product_events pe LEFT JOIN users u ON u.id=pe.user_id LEFT JOIN workspaces w ON w.id=pe.workspace_id WHERE ${s.sql} ORDER BY pe.created_at DESC,pe.id DESC LIMIT ?`,[...s.params,lim]);return rows.map(r=>({...r,properties:parseJson(r.properties_json)}))}
async function getUserDetail(workspaceId,userId,opts={}){const user=await get(`SELECT id,public_id,display_name,email FROM users WHERE id=?`,[userId]);if(!user)return null;const s=peScope(workspaceId,opts);const events=await all(`SELECT pe.id,pe.event_name,pe.event_category,pe.path,pe.entity_type,pe.entity_reference,pe.properties_json,pe.created_at,pe.session_id,w.name workspace_name FROM product_events pe LEFT JOIN workspaces w ON w.id=pe.workspace_id WHERE ${s.sql} AND pe.user_id=? ORDER BY pe.created_at DESC,pe.id DESC LIMIT 1000`,[...s.params,userId]);const p=period(opts);const sessions=await all(`SELECT id,created_at,last_seen_at,expires_at,revoked_at,user_agent FROM user_sessions WHERE user_id=? AND ${p.sql} ORDER BY created_at DESC LIMIT 500`,[userId,...p.params]);return{user,events:events.map(r=>({...r,properties:parseJson(r.properties_json)})),sessions:sessions.map(r=>({...r,...deviceFromUa(r.user_agent)}))}}
function stepMatches(e,step){return e.event_name===step.event&&(!step.path||String(e.path||'').includes(step.path))}function funnelCounts(events,steps){const by=new Map();for(const e of events){if(!e.session_id)continue;if(!by.has(e.session_id))by.set(e.session_id,[]);by.get(e.session_id).push(e)}return steps.map((step,i)=>{let count=0;for(const list of by.values()){let pos=-1,ok=true;for(let x=0;x<=i;x++){let found=-1;for(let k=pos+1;k<list.length;k++)if(stepMatches(list[k],steps[x])){found=k;break}if(found<0){ok=false;break}pos=found}if(ok)count++}return{step:step.label||step.event,event_name:step.event,sessions:count}})}
async function getFunnels(workspaceId,opts={}){const s=peScope(workspaceId,opts);const events=await all(`SELECT pe.session_id,pe.event_name,pe.path,pe.created_at FROM product_events pe WHERE ${s.sql} ORDER BY pe.session_id,pe.created_at,pe.id`,s.params);return[{key:'food_moment',label:'Food Moment erstellen',steps:funnelCounts(events,[{event:'page_view',path:'foodMomentCreate',label:'Erstellung geöffnet'},{event:'food_moment_created',label:'Food Moment gespeichert'}])},{key:'inspiration_to_recipe',label:'Inspiration → Rezept',steps:funnelCounts(events,[{event:'wallet_saved',label:'Inspiration gespeichert'},{event:'wallet_recipe_connected',label:'Mit Rezept verknüpft'}])},{key:'planning',label:'Wochenplanung',steps:funnelCounts(events,[{event:'page_view',path:'mealPlan',label:'Planung geöffnet'},{event:'planning_slot_saved',label:'Planung gespeichert'}])},{key:'shopping',label:'Inhalt → Einkauf',steps:funnelCounts(events,[{event:'page_view',path:'shopping',label:'Einkaufen geöffnet'},{event:'shopping_item_toggled',label:'Einkauf aktiv genutzt'}])}]}
module.exports={recordEvent,trackingMiddleware,getSummary,getLogins,getJourneys,getUserDetail,getFunnels};
